name: Build Phicomm-N1

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: '是否开启 SSH 定制插件 (输入 true 开启)'
        required: false
        default: 'true'

env:
  REPO_URL: https://github.com
  REPO_BRANCH: master
  DEVICE_NAME: phicomm-n1
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialization environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://is.gd)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$USER /workdir

    - name: Clone source code
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$USER /workdir
        git clone --depth 1 https://github.com /workdir/openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update & Install feeds
      run: cd openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event_name == 'workflow_dispatch')

    - name: Compile the firmware
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc) || make -j1 V=s
